import React, { useState } from 'react';
import { Copy, Check, Palette, Code, Eye } from 'lucide-react';
import { Tool } from '../../types';

interface TextDesignViewProps {
  tool: Tool;
  onToast: (msg: string) => void;
}

export const TextDesignView: React.FC<TextDesignViewProps> = ({ tool, onToast }) => {
  const [sampleText, setSampleText] = useState('');
  const [textColor, setTextColor] = useState('#007bff');
  const [bgColor, setBgColor] = useState('#ffffff');
  const [fontSize, setFontSize] = useState(36);
  const [fontWeight, setFontWeight] = useState('700');
  const [fontFamily, setFontFamily] = useState('Plus Jakarta Sans');
  const [gradientStart, setGradientStart] = useState('#007bff');
  const [gradientEnd, setGradientEnd] = useState('#ec4899');
  const [gradientAngle, setGradientAngle] = useState(90);
  const [shadowColor, setShadowColor] = useState('rgba(0, 0, 0, 0.35)');
  const [shadowX, setShadowX] = useState(3);
  const [shadowY, setShadowY] = useState(4);
  const [shadowBlur, setShadowBlur] = useState(8);
  const [outlineColor, setOutlineColor] = useState('#003366');
  const [outlineWidth, setOutlineWidth] = useState(2);
  const [lineHeight, setLineHeight] = useState(1.5);
  const [letterSpacing, setLetterSpacing] = useState(1);
  const [wordSpacing, setWordSpacing] = useState(2);
  const [copiedCSS, setCopiedCSS] = useState(false);
  const [copiedHTML, setCopiedHTML] = useState(false);

  const isGradient = tool.id === 'gradient-text-generator';
  const isShadow = tool.id === 'text-shadow-generator';
  const isOutline = tool.id === 'text-outline-generator';

  // Compute CSS styles object
  const previewStyle: React.CSSProperties = {
    fontFamily: `${fontFamily}, sans-serif`,
    fontSize: `${fontSize}px`,
    fontWeight: fontWeight,
    lineHeight: lineHeight,
    letterSpacing: `${letterSpacing}px`,
    wordSpacing: `${wordSpacing}px`,
  };

  if (isGradient) {
    previewStyle.backgroundImage = `linear-gradient(${gradientAngle}deg, ${gradientStart}, ${gradientEnd})`;
    previewStyle.WebkitBackgroundClip = 'text';
    previewStyle.WebkitTextFillColor = 'transparent';
  } else {
    previewStyle.color = textColor;
  }

  if (isShadow) {
    previewStyle.textShadow = `${shadowX}px ${shadowY}px ${shadowBlur}px ${shadowColor}`;
  }

  if (isOutline) {
    (previewStyle as unknown as Record<string, string>)['-webkit-text-stroke'] = `${outlineWidth}px ${outlineColor}`;
  }

  // Generate CSS Code snippet
  let cssRules = `/* CSS generated by Utility Bazaar */\n.styled-text {\n  font-family: '${fontFamily}', sans-serif;\n  font-size: ${fontSize}px;\n  font-weight: ${fontWeight};\n  line-height: ${lineHeight};\n  letter-spacing: ${letterSpacing}px;\n  word-spacing: ${wordSpacing}px;\n`;

  if (isGradient) {
    cssRules += `  background-image: linear-gradient(${gradientAngle}deg, ${gradientStart}, ${gradientEnd});\n  -webkit-background-clip: text;\n  -webkit-text-fill-color: transparent;\n`;
  } else {
    cssRules += `  color: ${textColor};\n`;
  }

  if (isShadow) {
    cssRules += `  text-shadow: ${shadowX}px ${shadowY}px ${shadowBlur}px ${shadowColor};\n`;
  }

  if (isOutline) {
    cssRules += `  -webkit-text-stroke: ${outlineWidth}px ${outlineColor};\n`;
  }

  cssRules += `}`;

  const htmlSnippet = `<div class="styled-text">\n  ${sampleText}\n</div>`;

  const handleCopy = (text: string, isCss: boolean) => {
    navigator.clipboard.writeText(text);
    if (isCss) {
      setCopiedCSS(true);
      setTimeout(() => setCopiedCSS(false), 2000);
    } else {
      setCopiedHTML(true);
      setTimeout(() => setCopiedHTML(false), 2000);
    }
    onToast('Code copied to clipboard!');
  };

  return (
    <div className="space-y-6">
      {/* Notice on plain text vs CSS styling */}
      <div className="rounded-xl border border-amber-200 dark:border-amber-900/60 bg-amber-50/70 dark:bg-amber-950/30 p-3.5 text-xs text-amber-900 dark:text-amber-200">
        ℹ️ <span className="font-bold">Important Note:</span> CSS colors, text-shadows, and gradients are web design styles rendered by browsers. When copied as plain text into notepad or SMS, colors cannot be preserved; copy the HTML/CSS code snippet below to use these styles in your website or graphic app!
      </div>

      {/* Live Preview Canvas */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <label className="text-sm font-bold text-neutral-900 dark:text-white flex items-center gap-1.5">
            <Eye className="h-4 w-4 text-indigo-500" />
            Live Typography Canvas:
          </label>
          <div className="flex items-center gap-2">
            <label className="text-xs text-neutral-500">Preview BG:</label>
            <input
              type="color"
              value={bgColor}
              onChange={(e) => setBgColor(e.target.value)}
              className="h-6 w-6 rounded cursor-pointer border-0 bg-transparent"
              title="Change preview background"
            />
          </div>
        </div>

        <div
          style={{ backgroundColor: bgColor, borderColor: 'var(--border-color)' }}
          className="min-h-48 rounded-2xl border p-8 flex items-center justify-center text-center overflow-hidden transition-colors"
        >
          {sampleText ? (
            <div style={previewStyle} className="max-w-full break-words">
              {sampleText}
            </div>
          ) : (
            <div className="text-slate-400 dark:text-slate-500 font-medium text-sm italic">
              (Neeche diye gaye box mein text likhein live preview dekhne ke liye)
            </div>
          )}
        </div>
      </div>

      {/* Sample Text Input */}
      <div>
        <div className="flex items-center justify-between mb-1.5">
          <label className="block text-xs font-bold text-slate-800 dark:text-slate-200">
            Aapka Text (Yahan Likhein):
          </label>
          {sampleText && (
            <button
              onClick={() => setSampleText('')}
              className="text-xs font-semibold text-rose-500 hover:text-rose-600 transition-colors"
            >
              Clear Text
            </button>
          )}
        </div>
        <input
          type="text"
          value={sampleText}
          onChange={(e) => setSampleText(e.target.value)}
          placeholder="Yahan apna text type karein (e.g. My Brand Name)..."
          className="w-full rounded-xl border p-3 text-base font-medium placeholder-slate-400 focus:ring-2 focus:ring-[#007bff] focus:outline-none transition-all"
          style={{
            backgroundColor: 'var(--card-bg)',
            borderColor: 'var(--border-color)',
            color: 'var(--text-color)',
            boxShadow: 'var(--shadow)',
          }}
        />
      </div>

      {/* Interactive Controls Panel */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 rounded-xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-800/40 p-5">
        {/* Font Family */}
        <div>
          <label className="block text-xs font-semibold text-neutral-700 dark:text-neutral-300 mb-1">Font Family:</label>
          <select
            value={fontFamily}
            onChange={(e) => setFontFamily(e.target.value)}
            className="w-full rounded-lg border border-neutral-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 px-3 py-2 text-sm text-neutral-900 dark:text-white"
          >
            <option value="Plus Jakarta Sans">Plus Jakarta Sans (Modern Clean)</option>
            <option value="JetBrains Mono">JetBrains Mono (Monospace)</option>
            <option value="Georgia">Georgia (Serif Editorial)</option>
            <option value="Arial">Arial (Standard Sans)</option>
            <option value="Impact">Impact (Bold Display)</option>
            <option value="Courier New">Courier New (Typewriter)</option>
            <option value="Trebuchet MS">Trebuchet MS (Geometric)</option>
          </select>
        </div>

        {/* Font Size */}
        <div>
          <div className="flex justify-between text-xs font-semibold text-neutral-700 dark:text-neutral-300 mb-1">
            <span>Font Size:</span>
            <span>{fontSize}px</span>
          </div>
          <input
            type="range"
            min="12"
            max="96"
            value={fontSize}
            onChange={(e) => setFontSize(parseInt(e.target.value))}
            className="w-full accent-indigo-600"
          />
        </div>

        {/* Font Weight */}
        <div>
          <label className="block text-xs font-semibold text-neutral-700 dark:text-neutral-300 mb-1">Font Weight:</label>
          <select
            value={fontWeight}
            onChange={(e) => setFontWeight(e.target.value)}
            className="w-full rounded-lg border border-neutral-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 px-3 py-2 text-sm text-neutral-900 dark:text-white"
          >
            <option value="300">Light (300)</option>
            <option value="400">Regular (400)</option>
            <option value="500">Medium (500)</option>
            <option value="600">SemiBold (600)</option>
            <option value="700">Bold (700)</option>
            <option value="800">Extra Bold (800)</option>
            <option value="900">Black (900)</option>
          </select>
        </div>

        {/* Text Color / Gradient Controls */}
        {isGradient ? (
          <>
            <div>
              <label className="block text-xs font-semibold text-neutral-700 dark:text-neutral-300 mb-1">Gradient Start:</label>
              <div className="flex items-center gap-2">
                <input
                  type="color"
                  value={gradientStart}
                  onChange={(e) => setGradientStart(e.target.value)}
                  className="h-9 w-12 rounded cursor-pointer border border-neutral-300 dark:border-neutral-700 bg-white"
                />
                <input
                  type="text"
                  value={gradientStart}
                  onChange={(e) => setGradientStart(e.target.value)}
                  className="flex-1 rounded-lg border border-neutral-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 px-2 py-1.5 text-xs uppercase"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-semibold text-neutral-700 dark:text-neutral-300 mb-1">Gradient End:</label>
              <div className="flex items-center gap-2">
                <input
                  type="color"
                  value={gradientEnd}
                  onChange={(e) => setGradientEnd(e.target.value)}
                  className="h-9 w-12 rounded cursor-pointer border border-neutral-300 dark:border-neutral-700 bg-white"
                />
                <input
                  type="text"
                  value={gradientEnd}
                  onChange={(e) => setGradientEnd(e.target.value)}
                  className="flex-1 rounded-lg border border-neutral-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 px-2 py-1.5 text-xs uppercase"
                />
              </div>
            </div>

            <div>
              <div className="flex justify-between text-xs font-semibold text-neutral-700 dark:text-neutral-300 mb-1">
                <span>Gradient Angle:</span>
                <span>{gradientAngle}°</span>
              </div>
              <input
                type="range"
                min="0"
                max="360"
                value={gradientAngle}
                onChange={(e) => setGradientAngle(parseInt(e.target.value))}
                className="w-full accent-indigo-600"
              />
            </div>
          </>
        ) : (
          <div>
            <label className="block text-xs font-semibold text-neutral-700 dark:text-neutral-300 mb-1">Text Color:</label>
            <div className="flex items-center gap-2">
              <input
                type="color"
                value={textColor}
                onChange={(e) => setTextColor(e.target.value)}
                className="h-9 w-12 rounded cursor-pointer border border-neutral-300 dark:border-neutral-700 bg-white"
              />
              <input
                type="text"
                value={textColor}
                onChange={(e) => setTextColor(e.target.value)}
                className="flex-1 rounded-lg border border-neutral-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 px-2 py-1.5 text-xs uppercase"
              />
            </div>
          </div>
        )}

        {/* Text Shadow Controls */}
        {isShadow && (
          <>
            <div>
              <div className="flex justify-between text-xs font-semibold text-neutral-700 dark:text-neutral-300 mb-1">
                <span>Shadow Blur:</span>
                <span>{shadowBlur}px</span>
              </div>
              <input
                type="range"
                min="0"
                max="30"
                value={shadowBlur}
                onChange={(e) => setShadowBlur(parseInt(e.target.value))}
                className="w-full accent-indigo-600"
              />
            </div>
            <div>
              <div className="flex justify-between text-xs font-semibold text-neutral-700 dark:text-neutral-300 mb-1">
                <span>Offset X & Y:</span>
                <span>{shadowX}px, {shadowY}px</span>
              </div>
              <input
                type="range"
                min="-20"
                max="20"
                value={shadowX}
                onChange={(e) => setShadowX(parseInt(e.target.value))}
                className="w-full accent-indigo-600"
              />
            </div>
          </>
        )}

        {/* Outline Controls */}
        {isOutline && (
          <div>
            <div className="flex justify-between text-xs font-semibold text-neutral-700 dark:text-neutral-300 mb-1">
              <span>Outline Width:</span>
              <span>{outlineWidth}px</span>
            </div>
            <input
              type="range"
              min="1"
              max="10"
              value={outlineWidth}
              onChange={(e) => setOutlineWidth(parseInt(e.target.value))}
              className="w-full accent-indigo-600"
            />
          </div>
        )}

        {/* Letter Spacing */}
        <div>
          <div className="flex justify-between text-xs font-semibold text-neutral-700 dark:text-neutral-300 mb-1">
            <span>Letter Spacing:</span>
            <span>{letterSpacing}px</span>
          </div>
          <input
            type="range"
            min="-2"
            max="15"
            value={letterSpacing}
            onChange={(e) => setLetterSpacing(parseInt(e.target.value))}
            className="w-full accent-indigo-600"
          />
        </div>

        {/* Line Height */}
        <div>
          <div className="flex justify-between text-xs font-semibold text-neutral-700 dark:text-neutral-300 mb-1">
            <span>Line Height:</span>
            <span>{lineHeight}</span>
          </div>
          <input
            type="range"
            min="0.8"
            max="3"
            step="0.1"
            value={lineHeight}
            onChange={(e) => setLineHeight(parseFloat(e.target.value))}
            className="w-full accent-indigo-600"
          />
        </div>
      </div>

      {/* Generated Code Export Tabs */}
      <div className="space-y-4">
        <div>
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-bold uppercase tracking-wider text-neutral-500 flex items-center gap-1.5">
              <Code className="h-3.5 w-3.5" />
              Generated CSS Code:
            </span>
            <button
              onClick={() => handleCopy(cssRules, true)}
              className="flex items-center gap-1 rounded-lg border border-neutral-200 dark:border-neutral-700 bg-white dark:bg-neutral-800 px-3 py-1.5 text-xs font-semibold text-neutral-700 dark:text-neutral-200 hover:bg-neutral-50 dark:hover:bg-neutral-700"
            >
              {copiedCSS ? <Check className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}
              {copiedCSS ? 'Copied' : 'Copy CSS'}
            </button>
          </div>
          <pre className="rounded-xl border border-neutral-200 dark:border-neutral-800 bg-neutral-900 p-4 text-xs font-mono text-emerald-400 overflow-x-auto">
            {cssRules}
          </pre>
        </div>

        <div>
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-bold uppercase tracking-wider text-neutral-500 flex items-center gap-1.5">
              <Palette className="h-3.5 w-3.5" />
              HTML Usage:
            </span>
            <button
              onClick={() => handleCopy(htmlSnippet, false)}
              className="flex items-center gap-1 rounded-lg border border-neutral-200 dark:border-neutral-700 bg-white dark:bg-neutral-800 px-3 py-1.5 text-xs font-semibold text-neutral-700 dark:text-neutral-200 hover:bg-neutral-50 dark:hover:bg-neutral-700"
            >
              {copiedHTML ? <Check className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}
              {copiedHTML ? 'Copied' : 'Copy HTML'}
            </button>
          </div>
          <pre className="rounded-xl border border-neutral-200 dark:border-neutral-800 bg-neutral-900 p-4 text-xs font-mono text-cyan-300 overflow-x-auto">
            {htmlSnippet}
          </pre>
        </div>
      </div>
    </div>
  );
};
